# kids_calendar/config.yaml

kids:
  - name: "Mark"
    calendar_url: "https://www.dasd.org/calendar/calendar_372.ics"
    encores:
      - day: A
        classes:  Gym
      - day: B
        classes: Library
      - day: C
        classes:  Music
      - day: D
        classes:  Gym
      - day: E
        classes:  iDesign
      - day: F
        classes:  Art

  - name: "Sofya"
    calendar_url: "https://www.dasd.org/calendar/calendar_372.ics"
    encores:
      - day: A
        classes:  A
      - day: B
        classes: B
      - day: C
        classes:  C
      - day: D
        classes:  D
      - day: E
        classes:  E
      - day: F
        classes:  F
